/* PlayStation(R)Mobile SDK 1.11.01
 * Copyright (C) 2013 Sony Computer Entertainment Inc.
 * All Rights Reserved.
 */
//空・空
//------------------------------------------------------------------------------------------
void main(
	float2 in v_TexCoord00			: TEXCOORD0,

	float4 out Color				: COLOR,

	uniform sampler2D Texture00,
	uniform float RateLight
)
{
	Color = tex2D( Texture00, v_TexCoord00 )/(1+4*RateLight);
}
